model:
  embedding_dim: 50
  reg_lambda: 0.001
  checkpoint_path: "../models/checkpoints/best_model.pt"

training:
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 15
  dropout: 0.2
  early_stopping:
    patience: 5
    min_delta: 0.0001

api:
  host: "0.0.0.0"
  port: 8080

data:
  min_user_interactions: 5
  min_item_interaction: 5
  validation_size: 0.1
  test_size: 0.1
  mappings:
    user_mapping: "../data/mappings/user_mapping.pkl"
    item_mapping: "../data/mappings/items_mapping.pkl"

preprocessing:
  remove_duplicates: true
  normalize_ratings: true