model:
  embedding_dim: 150
  reg_lambda: 0.01

training:
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 20

api:
  host: "0.0.0.0"
  port: 8080

data:
  min_user_interactions: 5
  min_item_interaction: 5
  validation_size: 0.1
  test_size: 0.1

preprocessing:
  remove_duplicates: true
  normalize_ratings: true